
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Define the fonts using localFont
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata declaration
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Ensure geistSans and geistMono are in scope in this function
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
